; ROM0 inventory wrappers and money transaction helpers.
; 80 bytes in every release; control-flow skeleton is identical.

IF DEF(_JP)
    DEF INV_SUBTRACT_AMOUNT_PAID EQU $6bcf
    DEF INV_BANKSWITCH EQU $3636
    DEF INV_W_PLAYER_MONEY_PLUS2 EQU $d2cd
    DEF INV_PREDEF EQU $3eb1
    DEF INV_W_TEXTBOX_ID EQU $d0ea
    DEF INV_DISPLAY_TEXTBOX_ID EQU $3146
    DEF INV_PLAY_SOUND_WAIT EQU $379e
    DEF INV_WAIT_SOUND EQU $37a6
    DEF INV_REMOVE_ITEM EQU $4eed
    DEF INV_ADD_ITEM EQU $4e7d
    SECTION "ROM0 inventory", ROM0[$2bf3]
ELIF DEF(_EN)
    DEF INV_SUBTRACT_AMOUNT_PAID EQU $6b21
    DEF INV_BANKSWITCH EQU $35d6
    DEF INV_W_PLAYER_MONEY_PLUS2 EQU $d349
    DEF INV_PREDEF EQU $3e6d
    DEF INV_W_TEXTBOX_ID EQU $d125
    DEF INV_DISPLAY_TEXTBOX_ID EQU $30e8
    DEF INV_PLAY_SOUND_WAIT EQU $3740
    DEF INV_WAIT_SOUND EQU $3748
    DEF INV_REMOVE_ITEM EQU $4e74
    DEF INV_ADD_ITEM EQU $4e04
    SECTION "ROM0 inventory", ROM0[$2b96]
ELIF DEF(_DE)
    DEF INV_SUBTRACT_AMOUNT_PAID EQU $6b41
    DEF INV_BANKSWITCH EQU $35f0
    DEF INV_W_PLAYER_MONEY_PLUS2 EQU $d34e
    DEF INV_PREDEF EQU $3e87
    DEF INV_W_TEXTBOX_ID EQU $d12a
    DEF INV_DISPLAY_TEXTBOX_ID EQU $3102
    DEF INV_PLAY_SOUND_WAIT EQU $375a
    DEF INV_WAIT_SOUND EQU $3762
    DEF INV_REMOVE_ITEM EQU $4e74
    DEF INV_ADD_ITEM EQU $4e04
    SECTION "ROM0 inventory", ROM0[$2bb0]
ELIF DEF(_FR)
    DEF INV_SUBTRACT_AMOUNT_PAID EQU $6bb4
    DEF INV_BANKSWITCH EQU $35f3
    DEF INV_W_PLAYER_MONEY_PLUS2 EQU $d34e
    DEF INV_PREDEF EQU $3e8a
    DEF INV_W_TEXTBOX_ID EQU $d12a
    DEF INV_DISPLAY_TEXTBOX_ID EQU $3105
    DEF INV_PLAY_SOUND_WAIT EQU $375d
    DEF INV_WAIT_SOUND EQU $3765
    DEF INV_REMOVE_ITEM EQU $4e74
    DEF INV_ADD_ITEM EQU $4e04
    SECTION "ROM0 inventory", ROM0[$2bac]
ELIF DEF(_IT)
    DEF INV_SUBTRACT_AMOUNT_PAID EQU $6b74
    DEF INV_BANKSWITCH EQU $35ee
    DEF INV_W_PLAYER_MONEY_PLUS2 EQU $d34e
    DEF INV_PREDEF EQU $3e85
    DEF INV_W_TEXTBOX_ID EQU $d12a
    DEF INV_DISPLAY_TEXTBOX_ID EQU $3100
    DEF INV_PLAY_SOUND_WAIT EQU $3758
    DEF INV_WAIT_SOUND EQU $3760
    DEF INV_REMOVE_ITEM EQU $4e74
    DEF INV_ADD_ITEM EQU $4e04
    SECTION "ROM0 inventory", ROM0[$2bb0]
ELIF DEF(_ES)
    DEF INV_SUBTRACT_AMOUNT_PAID EQU $6b8e
    DEF INV_BANKSWITCH EQU $35f5
    DEF INV_W_PLAYER_MONEY_PLUS2 EQU $d34e
    DEF INV_PREDEF EQU $3e8c
    DEF INV_W_TEXTBOX_ID EQU $d12a
    DEF INV_DISPLAY_TEXTBOX_ID EQU $3107
    DEF INV_PLAY_SOUND_WAIT EQU $375f
    DEF INV_WAIT_SOUND EQU $3767
    DEF INV_REMOVE_ITEM EQU $4e74
    DEF INV_ADD_ITEM EQU $4e04
    SECTION "ROM0 inventory", ROM0[$2baf]
ELSE
    FAIL "Define exactly one release symbol"
ENDC

SubtractAmountPaidFromMoney::
    ld b, $01
    ld hl, INV_SUBTRACT_AMOUNT_PAID
    jp INV_BANKSWITCH

AddAmountSoldToMoney::
    ld de, INV_W_PLAYER_MONEY_PLUS2
    ld hl, $ffa1
    ld c, 3
    ld a, $0b
    call INV_PREDEF
    ld a, $13
    ld [INV_W_TEXTBOX_ID], a
    call INV_DISPLAY_TEXTBOX_ID
    ld a, $b2
    call INV_PLAY_SOUND_WAIT
    jp INV_WAIT_SOUND

RemoveItemFromInventory::
    ldh a, [$ffb8]
    push af
    ld a, $03
    ldh [$ffb8], a
    ld [$2000], a
    call INV_REMOVE_ITEM
    pop af
    ldh [$ffb8], a
    ld [$2000], a
    ret

AddItemToInventory::
    push bc
    ldh a, [$ffb8]
    push af
    ld a, $03
    ldh [$ffb8], a
    ld [$2000], a
    call INV_ADD_ITEM
    pop bc
    ld a, b
    ldh [$ffb8], a
    ld [$2000], a
    pop bc
    ret

PURGE INV_SUBTRACT_AMOUNT_PAID
PURGE INV_BANKSWITCH
PURGE INV_W_PLAYER_MONEY_PLUS2
PURGE INV_PREDEF
PURGE INV_W_TEXTBOX_ID
PURGE INV_DISPLAY_TEXTBOX_ID
PURGE INV_PLAY_SOUND_WAIT
PURGE INV_WAIT_SOUND
PURGE INV_REMOVE_ITEM
PURGE INV_ADD_ITEM
