; ROM0 start-menu dispatcher.
; The 178-byte opcode skeleton is identical in all six Blue releases;
; release-specific ROM/WRAM operands are isolated below.

IF DEF(_JP)
    DEF SM_W_WALK_BIKE_SURF EQU $d67f
    DEF SM_W_WALK_BIKE_SURF_COPY EQU $d0df
    DEF SM_BANKSWITCH EQU $3636
    DEF SM_DRAW_START_MENU EQU $73d3
    DEF SM_PRINT_SAFARI_STEPS EQU $4567
    DEF SM_HANDLE_MENU_INPUT EQU $3b1c
    DEF SM_W_POKEDEX_EVENT_BYTE EQU $d6ca
    DEF SM_ERASE_MENU_CURSOR EQU $3c3d
    DEF SM_PLACE_UNFILLED_CURSOR EQU $3c30
    DEF SM_SAVE_SCREEN_TILES EQU $3754
    DEF SM_MENU_POKEDEX EQU $7518
    DEF SM_MENU_POKEMON EQU $752c
    DEF SM_MENU_ITEM EQU $7803
    DEF SM_MENU_TRAINER EQU $797d
    DEF SM_MENU_SAVE_RESET EQU $7b03
    DEF SM_MENU_OPTION EQU $7b16
    DEF SM_LOAD_TEXTBOX_TILES EQU $3700
    DEF SM_CLOSE_TEXT_DISPLAY EQU $2a06
    SECTION "ROM0 start menu", ROM0[$2b2a]
ELIF DEF(_EN)
    DEF SM_W_WALK_BIKE_SURF EQU $d700
    DEF SM_W_WALK_BIKE_SURF_COPY EQU $d11a
    DEF SM_BANKSWITCH EQU $35d6
    DEF SM_DRAW_START_MENU EQU $710b
    DEF SM_PRINT_SAFARI_STEPS EQU $452f
    DEF SM_HANDLE_MENU_INPUT EQU $3abe
    DEF SM_W_POKEDEX_EVENT_BYTE EQU $d74b
    DEF SM_ERASE_MENU_CURSOR EQU $3bf9
    DEF SM_PLACE_UNFILLED_CURSOR EQU $3bec
    DEF SM_SAVE_SCREEN_TILES EQU $36f4
    DEF SM_MENU_POKEDEX EQU $7095
    DEF SM_MENU_POKEMON EQU $70a9
    DEF SM_MENU_ITEM EQU $7302
    DEF SM_MENU_TRAINER EQU $7460
    DEF SM_MENU_SAVE_RESET EQU $75e3
    DEF SM_MENU_OPTION EQU $75f6
    DEF SM_LOAD_TEXTBOX_TILES EQU $36a0
    DEF SM_CLOSE_TEXT_DISPLAY EQU $29e8
    SECTION "ROM0 start menu", ROM0[$2acd]
ELIF DEF(_DE)
    DEF SM_W_WALK_BIKE_SURF EQU $d705
    DEF SM_W_WALK_BIKE_SURF_COPY EQU $d11f
    DEF SM_BANKSWITCH EQU $35f0
    DEF SM_DRAW_START_MENU EQU $712b
    DEF SM_PRINT_SAFARI_STEPS EQU $452f
    DEF SM_HANDLE_MENU_INPUT EQU $3ad8
    DEF SM_W_POKEDEX_EVENT_BYTE EQU $d750
    DEF SM_ERASE_MENU_CURSOR EQU $3c13
    DEF SM_PLACE_UNFILLED_CURSOR EQU $3c06
    DEF SM_SAVE_SCREEN_TILES EQU $370e
    DEF SM_MENU_POKEDEX EQU $7098
    DEF SM_MENU_POKEMON EQU $70ac
    DEF SM_MENU_ITEM EQU $7305
    DEF SM_MENU_TRAINER EQU $7463
    DEF SM_MENU_SAVE_RESET EQU $75e4
    DEF SM_MENU_OPTION EQU $75f7
    DEF SM_LOAD_TEXTBOX_TILES EQU $36ba
    DEF SM_CLOSE_TEXT_DISPLAY EQU $29e8
    SECTION "ROM0 start menu", ROM0[$2ae7]
ELIF DEF(_FR)
    DEF SM_W_WALK_BIKE_SURF EQU $d705
    DEF SM_W_WALK_BIKE_SURF_COPY EQU $d11f
    DEF SM_BANKSWITCH EQU $35f3
    DEF SM_DRAW_START_MENU EQU $719e
    DEF SM_PRINT_SAFARI_STEPS EQU $452f
    DEF SM_HANDLE_MENU_INPUT EQU $3adb
    DEF SM_W_POKEDEX_EVENT_BYTE EQU $d750
    DEF SM_ERASE_MENU_CURSOR EQU $3c16
    DEF SM_PLACE_UNFILLED_CURSOR EQU $3c09
    DEF SM_SAVE_SCREEN_TILES EQU $3711
    DEF SM_MENU_POKEDEX EQU $70a3
    DEF SM_MENU_POKEMON EQU $70b7
    DEF SM_MENU_ITEM EQU $7310
    DEF SM_MENU_TRAINER EQU $746e
    DEF SM_MENU_SAVE_RESET EQU $75f2
    DEF SM_MENU_OPTION EQU $7605
    DEF SM_LOAD_TEXTBOX_TILES EQU $36bd
    DEF SM_CLOSE_TEXT_DISPLAY EQU $29e4
    SECTION "ROM0 start menu", ROM0[$2ae3]
ELIF DEF(_IT)
    DEF SM_W_WALK_BIKE_SURF EQU $d705
    DEF SM_W_WALK_BIKE_SURF_COPY EQU $d11f
    DEF SM_BANKSWITCH EQU $35ee
    DEF SM_DRAW_START_MENU EQU $715e
    DEF SM_PRINT_SAFARI_STEPS EQU $452f
    DEF SM_HANDLE_MENU_INPUT EQU $3ad6
    DEF SM_W_POKEDEX_EVENT_BYTE EQU $d750
    DEF SM_ERASE_MENU_CURSOR EQU $3c11
    DEF SM_PLACE_UNFILLED_CURSOR EQU $3c04
    DEF SM_SAVE_SCREEN_TILES EQU $370c
    DEF SM_MENU_POKEDEX EQU $70b7
    DEF SM_MENU_POKEMON EQU $70cb
    DEF SM_MENU_ITEM EQU $7324
    DEF SM_MENU_TRAINER EQU $7482
    DEF SM_MENU_SAVE_RESET EQU $7608
    DEF SM_MENU_OPTION EQU $761b
    DEF SM_LOAD_TEXTBOX_TILES EQU $36b8
    DEF SM_CLOSE_TEXT_DISPLAY EQU $29e8
    SECTION "ROM0 start menu", ROM0[$2ae7]
ELIF DEF(_ES)
    DEF SM_W_WALK_BIKE_SURF EQU $d705
    DEF SM_W_WALK_BIKE_SURF_COPY EQU $d11f
    DEF SM_BANKSWITCH EQU $35f5
    DEF SM_DRAW_START_MENU EQU $7178
    DEF SM_PRINT_SAFARI_STEPS EQU $452f
    DEF SM_HANDLE_MENU_INPUT EQU $3add
    DEF SM_W_POKEDEX_EVENT_BYTE EQU $d750
    DEF SM_ERASE_MENU_CURSOR EQU $3c18
    DEF SM_PLACE_UNFILLED_CURSOR EQU $3c0b
    DEF SM_SAVE_SCREEN_TILES EQU $3713
    DEF SM_MENU_POKEDEX EQU $70b5
    DEF SM_MENU_POKEMON EQU $70c9
    DEF SM_MENU_ITEM EQU $7322
    DEF SM_MENU_TRAINER EQU $7480
    DEF SM_MENU_SAVE_RESET EQU $7608
    DEF SM_MENU_OPTION EQU $761b
    DEF SM_LOAD_TEXTBOX_TILES EQU $36bf
    DEF SM_CLOSE_TEXT_DISPLAY EQU $29e7
    SECTION "ROM0 start menu", ROM0[$2ae6]
ELSE
    FAIL "Define exactly one release symbol"
ENDC

DEF SM_W_CURRENT_MENU_ITEM EQU $cc26
DEF SM_W_LAST_MENU_ITEM EQU $cc2a
DEF SM_W_SAVED_MENU_ITEM EQU $cc2d

DisplayStartMenu::
    ld a, $04
    ldh [$ffb8], a
    ld [$2000], a
    ld a, [SM_W_WALK_BIKE_SURF]
    ld [SM_W_WALK_BIKE_SURF_COPY], a
    ld a, $8f
    call PlaySound

RedisplayStartMenu::
    ld b, $01
    ld hl, SM_DRAW_START_MENU
    call SM_BANKSWITCH
    ld b, $03
    ld hl, SM_PRINT_SAFARI_STEPS
    call SM_BANKSWITCH
    call UpdateSprites
.loop
    call SM_HANDLE_MENU_INPUT
    ld b, a
    bit 6, a
    jr z, .checkIfDownPressed
    ld a, [SM_W_CURRENT_MENU_ITEM]
    and a
    jr nz, .loop
    ld a, [SM_W_LAST_MENU_ITEM]
    and a
    jr nz, .loop
    ld a, [SM_W_POKEDEX_EVENT_BYTE]
    bit 5, a
    ld a, 6
    jr nz, .wrapMenuItemId
    dec a
.wrapMenuItemId
    ld [SM_W_CURRENT_MENU_ITEM], a
    call SM_ERASE_MENU_CURSOR
    jr .loop
.checkIfDownPressed
    bit 7, a
    jr z, .buttonPressed
    ld a, [SM_W_POKEDEX_EVENT_BYTE]
    bit 5, a
    ld a, [SM_W_CURRENT_MENU_ITEM]
    ld c, 7
    jr nz, .checkIfPastBottom
    dec c
.checkIfPastBottom
    cp c
    jr nz, .loop
    xor a
    ld [SM_W_CURRENT_MENU_ITEM], a
    call SM_ERASE_MENU_CURSOR
    jr .loop
.buttonPressed
    call SM_PLACE_UNFILLED_CURSOR
    ld a, [SM_W_CURRENT_MENU_ITEM]
    ld [SM_W_SAVED_MENU_ITEM], a
    ld a, b
    and $0a
    jp nz, CloseStartMenu
    call SM_SAVE_SCREEN_TILES
    ld a, [SM_W_POKEDEX_EVENT_BYTE]
    bit 5, a
    ld a, [SM_W_CURRENT_MENU_ITEM]
    jr nz, .displayMenuItem
    inc a
.displayMenuItem
    cp 0
    jp z, SM_MENU_POKEDEX
    cp 1
    jp z, SM_MENU_POKEMON
    cp 2
    jp z, SM_MENU_ITEM
    cp 3
    jp z, SM_MENU_TRAINER
    cp 4
    jp z, SM_MENU_SAVE_RESET
    cp 5
    jp z, SM_MENU_OPTION

CloseStartMenu::
    call Joypad
    ldh a, [$ffb3]
    bit 0, a
    jr nz, CloseStartMenu
    call SM_LOAD_TEXTBOX_TILES
    jp SM_CLOSE_TEXT_DISPLAY

PURGE SM_W_WALK_BIKE_SURF
PURGE SM_W_WALK_BIKE_SURF_COPY
PURGE SM_BANKSWITCH
PURGE SM_DRAW_START_MENU
PURGE SM_PRINT_SAFARI_STEPS
PURGE SM_HANDLE_MENU_INPUT
PURGE SM_W_POKEDEX_EVENT_BYTE
PURGE SM_ERASE_MENU_CURSOR
PURGE SM_PLACE_UNFILLED_CURSOR
PURGE SM_SAVE_SCREEN_TILES
PURGE SM_MENU_POKEDEX
PURGE SM_MENU_POKEMON
PURGE SM_MENU_ITEM
PURGE SM_MENU_TRAINER
PURGE SM_MENU_SAVE_RESET
PURGE SM_MENU_OPTION
PURGE SM_LOAD_TEXTBOX_TILES
PURGE SM_CLOSE_TEXT_DISPLAY
PURGE SM_W_CURRENT_MENU_ITEM
PURGE SM_W_LAST_MENU_ITEM
PURGE SM_W_SAVED_MENU_ITEM
