; Generated by tools/disassemble_gb_cfg.py; do not edit by hand.

SECTION "Bootstrap CFG 1f3a", ROM0[$1f3a]

Block_1f3a::
    di
    xor a
    ldh [$ff00 + $0f], a
    ldh [$ff00 + $ff], a
    ldh [$ff00 + $43], a
    ldh [$ff00 + $42], a
    ldh [$ff00 + $01], a
    ldh [$ff00 + $02], a
    ldh [$ff00 + $4b], a
    ldh [$ff00 + $4a], a
    ldh [$ff00 + $06], a
    ldh [$ff00 + $07], a
    ldh [$ff00 + $47], a
    ldh [$ff00 + $48], a
    ldh [$ff00 + $49], a
    ld a, $80
    ldh [$ff00 + $40], a
    call $16c7
    ld sp, $dfff
    ld hl, $c000
    ld bc, $2000
    ld [hl], $00
    inc hl
    dec bc
    ld a, b
    or c
    jr nz $1f66

SECTION "Bootstrap CFG 1f6e", ROM0[$1f6e]

Block_1f6e::
    call $1fea
    ld hl, $ff80
    ld bc, $007f
    call $3740
    call $16e8
    ld a, $01
    ldh [$ff00 + $b8], a
    ld [$2000], a
    call $4b44
    xor a
    ldh [$ff00 + $d7], a
    ldh [$ff00 + $41], a
    ldh [$ff00 + $ae], a
    ldh [$ff00 + $af], a
    ldh [$ff00 + $0f], a
    ld a, $0d
    ldh [$ff00 + $ff], a
    ld a, $90
    ldh [$ff00 + $b0], a
    ldh [$ff00 + $4a], a
    ld a, $07
    ldh [$ff00 + $4b], a
    ld a, $ff
    ldh [$ff00 + $aa], a
    ld h, $98
    call $1cd6
    ld h, $9c
    call $1cd6
    ld a, $e3
    ldh [$ff00 + $40], a
    ld a, $10
    ldh [$ff00 + $8a], a
    call $1ff4
    ei
    ld a, $40
    call $3eb1
    ld a, $1f
    ld [$c0ef], a
    ld [$c0f0], a
    ld a, $9c
    ldh [$ff00 + $bd], a
    xor a
    ldh [$ff00 + $bc], a
    dec a
    ld [$cfb2], a
    ld a, $32
    call $3eb1
    call $16c7
    call $1fea
    call $3e20
    call $16e8
    ld a, $e3
    ldh [$ff00 + $40], a
    jp $42d6
