; Generated by tools/disassemble_gb_cfg.py; do not edit by hand.

SECTION "DE Startup Dispatch 0150", ROM0[$0150]

Block_0150::
    cp $11
    jr z $0157

SECTION "DE Startup Dispatch 0154", ROM0[$0154]

Block_0154::
    xor a
    jr $0159

SECTION "DE Startup Dispatch 0157", ROM0[$0157]

Block_0157::
    ld a, $00
    ld [$cf1f], a
    jp $1f54
